@startuml
class com.example.myapplication1.GenerateQrCode {
~ ArrayList<Bitmap> qrCodes
~ ActivityGenerateQrCodeBinding binding
~ DbHandler dbHandler
# void onCreate(Bundle)
- Bitmap generateQrCode(String)
+ boolean onOptionsItemSelected(MenuItem)
}
class com.example.myapplication1.NewBill {
~ ActivityNewBillBinding binding
~ ArrayList<ProductModel> productsArray
~ CustomerModel customerModel
~ int chiledId
~ DbHandler dbHandler
# void onCreate(Bundle)
+ boolean onOptionsItemSelected(MenuItem)
+ void addProductPressed(View)
- void addProView(View)
- void removeProView(View)
- void proSpinner(View,ImageView)
- void hideProView(View,ImageView)
- void ifPressedAndProductFieldsAreEmpty(EditText)
- void PriceConditions(EditText)
- void setConditionsToProduct(View)
- void readDataFromView()
- ArrayList<Boolean> checkProduct()
- Boolean productIsRight()
+ {static} boolean AreAllTrue(ArrayList<Boolean>)
+ void MoveToBill(View)
+ void onClick(View)
- void hideKeyBoard(View)
- void showKeyBoard()
+ void sendData(String)
+ void closeFragment()
+ void onBackPressed()
+ void buAddCus(View)
+ void getCusName(String)
}
class com.example.myapplication1.Bill {
~ CustomerModel customerBill
~ ArrayList<ProductModel> productsArray
~ DbHandler dbHandler
~ ActivityBillBinding binding
~ boolean flag
# void onCreate(Bundle)
- void addProView()
- void getDataToFromAddCustomerActivity()
- String getCurrentTime()
- void quantityIsRight(EditText)
- void numberOfInstallmentsIsRight(EditText)
- boolean AllQuantityIsRight()
+ void calcTotalThenSaveAllData(View)
- void resetBill()
+ void onFocusChange(View,boolean)
+ void hideKeyBoard(View)
+ void onClick(View)
+ boolean onOptionsItemSelected(MenuItem)
}
class com.example.myapplication1.AddCustomer {
~ ActivityAddCustomerBinding binding
~ CustomerModel customer
~ DbHandler dbHandler
# void onCreate(Bundle)
+ boolean onOptionsItemSelected(MenuItem)
- void setConditionsToCustomer()
- void readDataFromView()
- void NameConditions(EditText)
- void AgeConditions(EditText)
- void JopConditions(EditText)
- void GenderConditions(EditText)
- void IDCardConditions(EditText)
- void PhoneNumberConditions(EditText)
- void AddressConditions(EditText)
- Boolean customerIsRight()
- void ifPressedAndFieldsAreEmpty(EditText,EditText,EditText,EditText,EditText,EditText,EditText)
+ void onClick(View)
- void hideKeyBoard(View)
+ void cuSave(View)
}
class com.example.myapplication1.AddExistProduct {
~ String qrcode
~ DbHandler dbHandler
~ ActivityAddExistProductBinding binding
# void onCreate(Bundle)
+ void buSavePro(View)
+ boolean onOptionsItemSelected(MenuItem)
}
class com.example.myapplication1.MainActivity {
~ ActivityMainBinding binding
~ DbHandler dbHandler
~ Toolbar toolbar
# void onCreate(Bundle)
+ void onRequestPermissionsResult(int,String[],int[])
+ void onClick(View)
}
class com.example.myapplication1.ManageProducts {
~ ActivityManageProductSBinding binding
+ {static} DbHandler dbHandler
# void onCreate(Bundle)
+ boolean onOptionsItemSelected(MenuItem)
}
class com.example.myapplication1.AddProduct {
~ ActivityAddProductBinding binding
~ ProductModel product
~ Bundle bundle
~ String[] countries
~ String[] section
~ String[] store
~ DatePickerDialog.OnDateSetListener setListener
~ DbHandler dbHandler
# void onCreate(Bundle)
- boolean allIsRight()
- void textLengthIsNull(EditText)
- boolean priceIsRight()
- boolean nameIsRight()
- boolean weightIsRight()
- boolean countryIsRight()
- boolean storeIsRight()
- boolean sectionIsRight()
- boolean expiryDateIsRight()
- boolean productionDateDateIsRight()
- void getDataFromForm()
+ void saveProduct(View)
- void hideKeyBoard(View)
+ void onClick(View)
+ void onRequestPermissionsResult(int,String[],int[])
+ int generateRandomNumber()
+ boolean isExist()
+ boolean onOptionsItemSelected(MenuItem)
+ void setDataToOrigenSpinner()
+ void setDataToSectionSpinner()
+ void setDataToStoreSpinner()
+ void handleOnUpdate()
+ void setProductionDate()
+ void setExpiryDate()
}
class com.example.myapplication1.ActivityCodeScanner {
- CodeScanner mCodeScanner
- CodeScannerView scannerView
~ int id
~ boolean flag
~ DbHandler dbHandler
~ ActivityCodeScannerBinding binding
# void onCreate(Bundle)
- void codeScanner()
# void onResume()
# void onPause()
}


androidx.appcompat.app.AppCompatActivity <|-- com.example.myapplication1.GenerateQrCode
com.example.myapplication1.OnClickListener <|.. com.example.myapplication1.NewBill
com.example.myapplication1.SendDataInterFace <|.. com.example.myapplication1.NewBill
com.example.myapplication1.SendCusNameInterFace <|.. com.example.myapplication1.NewBill
androidx.appcompat.app.AppCompatActivity <|-- com.example.myapplication1.NewBill
com.example.myapplication1.OnFocusChangeListener <|.. com.example.myapplication1.Bill
com.example.myapplication1.OnClickListener <|.. com.example.myapplication1.Bill
androidx.appcompat.app.AppCompatActivity <|-- com.example.myapplication1.Bill
com.example.myapplication1.OnClickListener <|.. com.example.myapplication1.AddCustomer
androidx.appcompat.app.AppCompatActivity <|-- com.example.myapplication1.AddCustomer
androidx.appcompat.app.AppCompatActivity <|-- com.example.myapplication1.AddExistProduct
com.example.myapplication1.OnClickListener <|.. com.example.myapplication1.MainActivity
androidx.appcompat.app.AppCompatActivity <|-- com.example.myapplication1.MainActivity
androidx.appcompat.app.AppCompatActivity <|-- com.example.myapplication1.ManageProducts
com.example.myapplication1.OnClickListener <|.. com.example.myapplication1.AddProduct
androidx.appcompat.app.AppCompatActivity <|-- com.example.myapplication1.AddProduct
androidx.appcompat.app.AppCompatActivity <|-- com.example.myapplication1.ActivityCodeScanner
@enduml