@startuml
class com.example.myapplication1.DataBase.DbHandler {
- {static} int VERSION
- {static} String DATABASE_NAME
- {static} String CUSTOMER_TABLE
- {static} String PRODUCT_TABLE
- {static} String BILL_TABLE
- {static} String SOLD_PRODUCT_TABLE
- {static} String PRODUCT_QUANTITY_TABLE
- {static} String ID
- {static} String NAME
- {static} String ID_CARD
- {static} String JOP
- {static} String AGE
- {static} String ADDRESS
- {static} String PHONE_NUMBER
- {static} String GENDER
- {static} String PURCHASING_PRICE
- {static} String CUS_ID
- {static} String COUNTRY_OF_ORIGIN
- {static} String CODE
- {static} String PRODUCTION_DATE
- {static} String EXPIRY_DATE
- {static} String SECTION
- {static} String STORE
- {static} String WEIGHT
- {static} String DATE
- {static} String TOTAL
- {static} String PAY_METHOD
- {static} String CUS_NAME
- {static} String PRO_NAME
- {static} String BILL_ID
- {static} String PRICE
- {static} String QUANTITY
- {static} String CREATE_TABLE_CUSTOMER
- {static} String CREATE_TABLE_BILL
- {static} String CREATE_TABLE_SOLD_PRODUCT
- {static} String CREATE_TABLE_PRODUCT_QUANTITY
- {static} String CREATE_TABLE_PRODUCTS
+ void onCreate(SQLiteDatabase)
+ void onUpgrade(SQLiteDatabase,int,int)
+ void setValueProductQuantityTable(int)
+ void setProductQuantity(String,int)
+ void updateProduct(ProductModel)
+ int getProductQuantity(String)
+ void addCustomer(CustomerModel)
+ void addProduct(ProductModel)
- void setValueCustomerTable(SQLiteDatabase,CustomerModel)
- ContentValues setValueBillTable(SQLiteDatabase,Long)
- void setValueToSoldProductTable(SQLiteDatabase,Long,ArrayList<ProductModel>)
- void setValueProductTable(SQLiteDatabase,ProductModel)
- void dropAllTables()
- void dropProductTables()
- int getNameId(String)
+ ArrayList<CustomerModel> getAllCustomers()
+ ArrayList<Bill_Model> getAllBIlls()
+ ArrayList<ProductModel> getAllProducts()
+ void deleteProduct(String)
+ String getProductName(String)
+ List<QrCodeModel> getAllQrCode()
}


android.database.sqlite.SQLiteOpenHelper <|-- com.example.myapplication1.DataBase.DbHandler
@enduml